### PR TITLE
Added the docs for the 'tkn' and 'openshift-client' task, migrated Tasks to v1 and added release.sh file.

### PR DESCRIPTION
**Pull request by Senjuti256**
Added the docs for the 'tkn' and 'openshift-client' task. Also updated the versions of pipeline required for e2e to `v1 version.`

Signed off :- Senjuti <sde@redhat.com>

### CODE REVIEW

**Comment by Senjuti256** [comment]
@vdemeester

**Review by vdemeester — APPROVED** [review]
We also need to update the release script to copy those docs as `README.md` for each tasks, but that can be done in a follow-up.

**Comment by Senjuti256** [comment]
Do I need to update the release script to update the docs in README.md in this PR only @vdemeester ?

**Comment by Senjuti256** [comment]
Updated the PR by adding the release script to copy the docs as README.md for each task. @vdemeester

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
